;(function(module,mw,$,undefined){'use strict';var translations=$.extend(true,{ar:{and:'و',second:'ثانية',seconds:'ثواني',minute:'دقيقة',minutes:'دقائق',hour:'ساعة',hours:'ساعات',day:'يوم',days:'أيام'},be:{and:'і',second:'секунда',seconds:'секунд',minute:'хвіліна',minutes:'хвілін',hour:'гадзіну',hours:'гадзін',day:'дзень',days:'дзён'},ca:{and:'i',second:'segon',seconds:'segons',minute:'minut',minutes:'minuts',hour:'hora',hours:'hores',day:'dia',days:'dies'},de:{and:'und',second:'Sekunde',seconds:'Sekunden',minute:'Minute',minutes:'Minuten',hour:'Stunde',hours:'Stunden',day:'Tag',days:'Tage'},en:{and:'and',second:'second',seconds:'seconds',minute:'minute',minutes:'minutes',hour:'hour',hours:'hours',day:'day',days:'days'},el:{and:'και',second:'δευτερόλεπτο',seconds:'δευτερόλεπτα',minute:'λεπτό',minutes:'λεπτά',hour:'ώρα',hours:'ώρες',day:'ημέρα',days:
'ημέρες'},es:{and:'y',second:'segundo',seconds:'segundos',minute:'minuto',minutes:'minutos',hour:'hora',hours:'horas',day:'día',days:'días'},fr:{and:'et',second:'seconde',seconds:'secondes',minute:'minute',minutes:'minutes',hour:'heure',hours:'heures',day:'jour',days:'jours'},hu:{and:'és',second:'másodperc',seconds:'másodperc',minute:'perc',minutes:'perc',hour:'óra',hours:'óra',day:'nap',days:'nap'},id:{and:'dan',second:'detik',seconds:'detik',minute:'menit',minutes:'menit',hour:'jam',hours:'jam',day:'hari',days:'hari'},it:{and:'e',second:'secondo',seconds:'secondi',minute:'minuto',minutes:'minuti',hour:'ora',hours:'ore',day:'giorno',days:'giorni'},ja:{and:'',second:'秒',seconds:'秒',minute:'分',minutes:'分',hour:'時間',hours:'時間',day:'日',days:'日'},ms:{and:'dan',second:'saat',seconds:'saat',minute:'minit',minutes:'minit',hour:'jam',hours:'jam',day:'hari',days:'hari'},nl:{and:'en',second:'seconde',seconds:'seconden',minute:'minuut',minutes:'minuten',hour:'uur'
,hours:'uur',day:'dag',days:'dagen'},pl:{and:'i',second:'sekunda',seconds:'sekund(y)',minute:'minuta',minutes:'minut(y)',hour:'godzina',hours:'godzin(y)',day:'dzień',days:'dni'},pt:{and:'e',second:'segundo',seconds:'segundos',minute:'minuto',minutes:'minutos',hour:'hora',hours:'horas',day:'dia',days:'dias'},'pt-br':{and:'e',second:'segundo',seconds:'segundos',minute:'minuto',minutes:'minutos',hour:'hora',hours:'horas',day:'dia',days:'dias'},ro:{and:'și',second:'secundă',seconds:'secunde',minute:'minut',minutes:'minute',hour:'oră',hours:'ore',day:'zi',days:'zile',},ru:{and:'и',second:'секунда',seconds:'секунд',minute:'минута',minutes:'минут',hour:'час',hours:'часов',day:'день',days:'дней'},sr:{and:'i',second:'sekundu',seconds:'sekunde/-i',minute:'minutu',minutes:'minute/-a',hour:'sat',hours:'sata/-i',day:'dan',days:'dana'},tl:{and:'at',second:'segundo',seconds:'mga segundo',minute:'minuto',minutes:'mga minuto',hour:'oras',hours:'mga oras',day
:'araw',days:'mga araw'},tr:{and:'ve',second:'saniye',seconds:'saniye',minute:'dakika',minutes:'dakika',hour:'saat',hours:'saat',day:'gün',days:'gün'},uk:{and:'та',second:'секунда',seconds:'секунд',minute:'хвилина',minutes:'хвилин',hour:'годину',hours:'годин',day:'день',days:'днів'},vi:{and:'và',second:'giây',seconds:'giây',minute:'phút',minutes:'phút',hour:'giờ',hours:'giờ',day:'ngày',days:'ngày'},zh:{and:' ',second:'秒',seconds:'秒',minute:'分',minutes:'分',hour:'时',hours:'时',day:'天',days:'天'},'zh-tw':{and:' ',second:'秒',seconds:'秒',minute:'分',minutes:'分',hour:'時',hours:'時',day:'天',days:'天'},'zh-hk':{and:' ',second:'秒',seconds:'秒',minute:'分',minutes:'分',hour:'時',hours:'時',day:'天',days:'天'}},module.translations||{}),i18n=translations[mw.config.get('wgContentLanguage')]||translations.en;var countdowns=[];var NO_LEADING_ZEROS=1,SHORT_FORMAT=2,NO_ZEROS=4;function output(i,diff){var
delta,result,parts=[];delta=diff%60;result=' '+i18n[delta===1?'second':'seconds'];if(countdowns[i].opts&SHORT_FORMAT)result=result.charAt(1);parts.unshift(delta+result);diff=Math.floor(diff/60);delta=diff%60;result=' '+i18n[delta===1?'minute':'minutes'];if(countdowns[i].opts&SHORT_FORMAT)result=result.charAt(1);parts.unshift(delta+result);diff=Math.floor(diff/60);delta=diff%24;result=' '+i18n[delta===1?'hour':'hours'];if(countdowns[i].opts&SHORT_FORMAT)result=result.charAt(1);parts.unshift(delta+result);diff=Math.floor(diff/24);result=' '+i18n[diff===1?'day':'days'];if(countdowns[i].opts&SHORT_FORMAT)result=result.charAt(1);parts.unshift(diff+result);result=parts.pop();if(countdowns[i].opts&NO_LEADING_ZEROS){while(parts.length&&parts[0][0]==='0'){parts.shift();}}if(countdowns[i].opts&NO_ZEROS){parts=parts.filter(function(part){return part[0]!=='0';});}if(parts.length){if(countdowns[i].opts&SHORT_FORMAT){result=parts.join(' ')+' '+result;}else{result=parts.join(', ')+' '+i18n.and+' '+
result;}}countdowns[i].node.text(result);}function end(i){var c=countdowns[i].node.parent();switch(c.attr('data-end')){case'remove':c.remove();return true;case'stop':output(i,0);return true;case'toggle':var toggle=c.attr('data-toggle');if(toggle&&toggle=='next'){c.next().css('display','inline');c.css('display','none');return true;}if(toggle&&$(toggle).length){$(toggle).css('display','inline');c.css('display','none');return true;}break;case'callback':var callback=c.attr('data-callback');if(callback&&$.isFunction(module[callback])){output(i,0);module[callback].call(c);return true;}break;}countdowns[i].countup=!0;output(i,0);return false;}function update(){var now=Date.now();var countdownsToRemove=[];$.each(countdowns.slice(0),function(i,countdown){var diff=Math.floor((countdown.date-now)/1000);if(diff<=0&&!countdown.countup){if(end(i))countdownsToRemove.push(i);}else{output(i,Math.abs(diff));}});var x;while((x=countdownsToRemove.pop())!==undefined){countdowns.splice(x,1);}if(countdowns
.length){window.setTimeout(function(){update();},1000);}}function getOptions(node){var text=node.parent().attr('data-options'),opts=0;if(text){if(/no-leading-zeros/.test(text)){opts|=NO_LEADING_ZEROS;}if(/short-format/.test(text)){opts|=SHORT_FORMAT;}if(/no-zeros/.test(text)){opts|=NO_ZEROS;}}return opts;}function init(){var countdown=$('.countdown:not(.handled)');if(!countdown.length)return;$('.nocountdown').css('display','none');countdown.css('display','inline').find('.countdowndate').each(function(){var $this=$(this),date=(new Date($this.text())).valueOf();if(isNaN(date)){$this.text('BAD DATE');return;}countdowns.push({node:$this,opts:getOptions($this),date:date,});});countdown.addClass('handled');if(countdowns.length){update();}}mw.hook('wikipage.content').add(init);}(window.countdownTimer=window.countdownTimer||{},mediaWiki,jQuery));;window.dev=window.dev||{};dev.ReferencePopups=dev.ReferencePopups||{};dev.ReferencePopups.unload=dev.ReferencePopups.unload||function(){"use strict";
delete this.Popup;delete this.configure;if(this.unloadCore){this.unloadCore();}};(function(module,lang){"use strict";var i18n={en:{coreConfigureText:'Configure Reference Popups',coreConfigureHover:'Change settings for Reference Popups'},ar:{coreConfigureText:'اضبط تلميحات المراجع',coreConfigureHover:'اضبط إعدادات تلميح المراجع'},be:{coreConfigureText:'Налада усплываючых падказак',coreConfigureHover:'Змяніць налады усплываючых падказак'},ca:{coreConfigureText:'Configura referències emergents',coreConfigureHover:'Canviar la configuració de referències emergents'},de:{coreConfigureText:'Referenz-Popups konfigurieren',coreConfigureHover:'Einstellungsänderungen für Referenz-Popups'},el:{coreConfigureText:'Ρύθμιση Αναδυόμενων Αναφορών',coreConfigureHover:'Αλλαγή ρυθμίσεων για τις Αναδυόμενες Αναφορές'},es:{coreConfigureText:
'Configurar popups de referencias',coreConfigureHover:'Modificar la configuración de los popups de referencias'},fr:{coreConfigureText:'Configurer Popups de Référence',coreConfigureHover:'Modifier les préférences pour les Popups de Référence'},it:{coreConfigureText:'Configura le note a popup',coreConfigureHover:'Cambia le impostazioni per le note a popup'},ja:{coreConfigureText:'注釈ふきだしの設定',coreConfigureHover:'注釈ふきだしの設定を変更する'},ko:{coreConfigureText:'주석 말풍선 설정',coreConfigureHover:'주석 말풍선 설정하기'},nl:{coreConfigureText:'Configureer Referentie Popups',coreConfigureHover:'Wijzig de instellingen voor Referentie Popups'},pl:{coreConfigureText:'Skonfiguruj wyskakujące przypisy',coreConfigureHover:'Zmień ustawienia dla wyskakujących przypisów'},'pt-br':{coreConfigureText:'Configurar Popups de Referência',coreConfigureHover:'Mudar configurações para Popups de Referência'},ro:{coreConfigureText:
'Configurați popupurile de referință',coreConfigureHover:'Schimbă setările pentru popupurile de referință'},ru:{coreConfigureText:'Настройка всплывающих подсказок',coreConfigureHover:'Изменить настройки всплывающих подсказок'},tr:{coreConfigureText:'Referans Bildirimlerini Yapılandır',coreConfigureHover:'Referans Bildirimleri\'nin seçeneklerini değiştir'},uk:{coreConfigureText:'Налаштування спливаючих підказок',coreConfigureHover:'Змінити налаштування спливаючих підказок'},vi:{coreConfigureText:'Thiết Đặt Popup Tham Khảo',coreConfigureHover:'Thay đổi thiết đặt cho Popup Tham Khảo'},zh:{coreConfigureText:'设定参考资料弹窗',coreConfigureHover:'更改参考弹出窗口的设置'},'zh-hk':{coreConfigureText:'設定參考資料彈窗',coreConfigureHover:'更改參考彈出窗口的設置'},'zh-tw':{coreConfigureText:
'設定參考資料彈窗',coreConfigureHover:'更改參考彈出窗口的設置'}};var msg=module.messages=module.messages||{};for(var m in i18n.en){msg[m]=msg[m]||(i18n[lang]&&i18n[lang][m])||i18n.en[m];}})(dev.ReferencePopups,mediaWiki.config.get('wgUserLanguage'));(function(window,$,mw){"use strict";var module=window.dev.ReferencePopups;if(module.Popup){return $.noop;}var mwReady=$.Deferred(),mwDeps=['jquery.ui.position','jquery.effects.fold','jquery.ui.core','jquery.ui.widget'];mw.loader.load(mwDeps,null,true);mw.loader.using(mwDeps,mwReady.resolve,mwReady.reject);var colors=window.dev.colors||$.ajax({url:mw.config.get('wgLoadScript'),data:{mode:'articles',only:'scripts',articles:'u:dev:Colors/code.js'},dataType:'script',cache:!0});if(!module.cssLoaded){window.importArticle({type:'style',article:'u:dev:MediaWiki:ReferencePopups.css'});module.cssLoaded=!0;}var dfd=$.Deferred();module.Popup=dfd.promise();return function(callback){$.when(mwReady,colors).done(function(){dfd.
resolve(module.Popup=callback(module,window,$,mw,window.dev.colors));}).fail(function(){delete module.Popup;dfd.reject();});};}(window,jQuery,mediaWiki))(function(module,window,$,mw,Colors){"use strict";$.curCSS=$.curCSS||$.css;(function(color,Colors,mw,$){function ifOk(val,alt){return(val&&val!=='transparent'&&val!=='rgba(0, 0, 0, 0)')?val:alt;}function tryParse(val,alt){try{return Colors.parse(val);}catch(e){if(window.console){window.console.warn('Colors Parse Error ('+val+'): ',e,e.stack);}return Colors.parse(alt);}}function toRgba(color,alpha){return'rgba('+color.red()+','+color.green()+','+color.blue()+','+alpha+')';}if(mw.config.get('skin')==='oasis'){color.page=Colors.parse(Colors.wikia.page);color.pageBorder=Colors.parse(Colors.wikia.border);color.accent=Colors.parse(Colors.wikia.menu);color.popText=Colors.wikia.text;}else{var $content=$('#content');color.page=tryParse(ifOk($('#globalWrapper').css('backgroundColor'),$content.css('backgroundColor')),'white');color.pageBorder=
tryParse(ifOk($content.css('borderLeftColor'),$content.css('borderRightColor')),'#AAA');color.accent=tryParse(ifOk($('#footer').css('borderTopColor'),$('body').css('backgroundColor')),'#fabd23');color.popText=tryParse($('#mw-content-text').css('color'),'black');}var mixCol;if(color.page.isBright()){color.back=color.page.mix(mixCol='black',95).mix('blue',97);}else{color.back=color.page.mix(mixCol='white',95);}color.popEdge=color.accent.mix(color.pageBorder,90);color.backA=toRgba(color.back,0.95);color.backB=toRgba(color.back.mix(mixCol,99),0.95);color.backC=toRgba(color.back.mix(mixCol,97),0.95);Colors.css(
'\
	.refpopups-box {\
		background-color: $back;\
		color: $popText;\
		border-color: $popEdge;\
		background: -webkit-linear-gradient(30deg, $backA, $backB 15%, $backB 25%, $backA 40%, $backA 50%, $backB 60%, $backB 70%, $backC 70%, $backC 90%, $backA 92%);\
		background: linear-gradient(60deg, $backA, $backB 15%, $backB 25%, $backA 40%, $backA 50%, $backB 60%, $backB 70%, $backC 70%, $backC 90%, $backA 92%);\
	}\
	.refpopups-chevron-in {\
		border-top-color: $back;\
		border-top-color: $backA;\
	}\
	.refpopups-flipped > .refpopups-chevron-in {\
		border-bottom-color: $back;\
		border-bottom-color: $backA;\
	}\
	.refpopups-chevron-out {\
		border-top-color: $popEdge;\
	}\
	.refpopups-flipped > .refpopups-chevron-out {\
		border-bottom-color: $popEdge;\
	}',color);})(module.colors=module.colors||{},Colors,mw,$);var widgetId=0;$.widget('Lunarity.referencePopup',{options:{activateBy:'hover',hoverDelay:200,content:'',disabled:!1,visible:!1,animation:'fold',animSpeed:300,context:null
,escapeCloses:!0,extraClass:'',contentBoxClass:'',stickyHover:!1,open:null,close:null},_create:function(){if(!this.document){this.document=$(this.element[0].ownerDocument);this.window=$(this.document[0].defaultView||this.document[0].parentWindow);this.eventNamespace='.'+this.widgetBaseClass+widgetId++;}this._timeouts={};this._$popup=$('<div class="refpopups-popup" id="'+this.eventNamespace.substr(1)+'">'+'<div class="refpopups-chevron-out"></div>'+'<div class="refpopups-chevron-in"></div>'+'<div class="refpopups-box">'+'</div></div>').addClass(this.options.extraClass).find('> .refpopups-box').addClass(this.options.contentBoxClass).end();this.options.context=$(this.document.find(this.options.context)[0]);if(!this.options.context.length){this.options.context=$(this.document[0].body);}this._setOption('activateBy',this.options.activateBy==='click'?'click':'hover');this._updateContent();if(!this.options.disabled){this.options.disabled=!0;this.enable();}if(this.options.visible){this.
options.visible=!1;this.show();}},_clearTimeout:function(name){if(this._timeouts[name]!==null){window.clearTimeout(this._timeouts[name]);this._timeouts[name]=null;}},_setTimeout:function(name,callback,delay){this._clearTimeout(name);var me=this;this._timeouts[name]=window.setTimeout(function(){me._timeouts[name]=null;callback.call(me);},delay||0);},_installEvents:function(){var self=this,map,ns=this.eventNamespace;this._$popup.off(ns);this.element.off(ns);this._clearTimeout('open');this._clearTimeout('close');if(this.options.disabled){return;}if(this.options.activateBy==='hover'){map={};map['mouseenter'+ns]=function(){self._clearTimeout('close');};map['mouseleave'+ns]=function(ev){self._setTimeout('close',function(){this.hide(ev);},self.options.hoverDelay);};this._$popup.on(map);map={};map['mouseenter'+ns]=function(ev){self._clearTimeout('close');self._setTimeout('open',function(){this.show(ev);},self.options.hoverDelay);};map['mouseleave'+ns]=function(ev){self._clearTimeout('open')
;if(!self.options.stickyHover){self._setTimeout('close',function(){this.hide(ev);},self.options.hoverDelay);}};this.element.on(map);}var lastTouch;map={};map['touchEnd'+ns]=function(ev){lastTouch=ev.originalEvent;};map['click'+ns]=function(ev){if((self.options.activateBy!=='click'&&(!lastTouch||lastTouch.defaultPrevented))||self.options.disabled){return;}lastTouch=null;if(!self.options.visible){ev.preventDefault();self.show(ev);}else{self.hide(ev);}};if(this.options.escapeCloses){var onKeyUp=function(ev){if(ev.which===$.ui.keyCode.ESCAPE){self.hide(ev);}};map['keyup'+ns]=onKeyUp;this._$popup.on('keyup'+ns,onKeyUp);}this.element.on(map);map=null;},triggerHover:function(event){if(this.options.activateBy==='hover'){this._setTimeout('open',function(){this.show(event);},this.options.hoverDelay);}},destroy:function(){this.hide();this._$popup.remove();this.element.off(this.eventNamespace);return $.Widget.prototype.destroy.call(this);},_updateContent:function(val){val=val||this.options.content
||'';if(!val.jquery&&!val.nodeType){this.options.content=val=$($(this.document[0].createElement('div')).html(val).contents().unwrap());}this._$popup.find('> .refpopups-box').empty().append(val);},_describeAria:function(yes){var k='aria-describedby',val=this.element.attr(k),s=val?val.split(/\s+/g):[],id=this._$popup[0].id,at=$.inArray(id,s);if(at!==-1){if(!yes){s.splice(at,1);}}else if(yes){s.push(id);}val=s.join(' ');this.element[val?'attr':'removeAttr'](k,val);},show:function(event){if(this.options.visible||this.options.disabled){return;}this.options.context.append(this._$popup.stop(true,true));this._positionPopup();this._describeAria(true);if(this.options.animation){this._$popup.hide().show(this.options.animation,this.options.animSpeed);}var triggered=0,self=this,ns=this.eventNamespace;this.window.on('scroll'+ns+' resize'+ns,function adaptCallback(){if(++triggered!==1){return;}self._positionPopup();window.setTimeout(function(){var t=triggered;triggered=0;if(t>1&&self.options.visible)
{adaptCallback();}},100);});if(this.options.activateBy==='click'){this.document.on('click'+ns,function(ev){if(!$(ev.target).closest(self._$popup.add(self.element)).length){self.hide();}});}this.options.visible=!0;this._trigger('open',event);},hide:function(event){if(!this.options.visible){return;}this.document.off(this.eventNamespace);this.window.off(this.eventNamespace);if(this.options.animation){var $clone=this._$popup.clone();this._$popup.after($clone);$clone.hide(this.options.animation,this.options.animSpeed,function(){$clone.remove();});}this._$popup.detach();this._describeAria(false);this.options.visible=!1;this._trigger('close',event);},toggle:function(yesno){yesno=(yesno!==void 0?yesno:!this.options.visible);this[yesno?'show':'hide']();},_setOption:function(key,val){switch(key){case'disabled':if(val&&this.options.visible){this.hide();}this.options.disabled=!!val;this._installEvents();return;case'visible':this[val?'show':'hide']();return;case'activateBy':if(({hover:1,click:
1})[val]===1){this.options.activateBy=val;this._installEvents();}return;case'content':this.options.content=val;this._updateContent();return;case'context':return;case'extraClass':this._$popup[0].className='refpopups-popup';this._$popup.addClass(val);break;case'extraBoxClass':this._$popup.find('> .refpopups-box').prop('className','refpopups-box').addClass(val);break;}return $.Widget.prototype._setOption.call(this,key,val);},_positionPopup:function(){var $popup=this._$popup.removeClass('refpopups-flipped'),$this=this.element,$chevOut=$popup.find('> .refpopups-chevron-out'),chevOutHeight=0;if($chevOut.is(':visible')){chevOutHeight=$chevOut.position().top+$chevOut.outerHeight()-$popup.outerHeight();}$popup.position({my:'bottom',at:'top',of:$this,collision:'fit none',offset:'0 -'+chevOutHeight});var spaceAtTop=$this.offset().top,spaceAtBottom=spaceAtTop+$this[0].offsetHeight,popupHeight=$popup[0].offsetHeight+chevOutHeight,scroll=this.window.scrollTop();spaceAtTop=spaceAtTop-scroll;
spaceAtBottom=(scroll+this.window.height())-spaceAtBottom;if(spaceAtTop<popupHeight&&spaceAtTop<spaceAtBottom){$popup.addClass('refpopups-flipped').position({my:'top',at:'bottom',of:$this,collision:'fit none',offset:'0 '+chevOutHeight});}if(!chevOutHeight){return;}var $chevIn=$popup.find('> .refpopups-chevron-in'),myLoc=$this.offset().left-$popup.offset().left+$this.outerWidth()/2;$chevOut.css('left',(myLoc-$chevOut.outerWidth()/2)+'px');$chevIn.css('left',(myLoc-$chevIn.outerWidth()/2)+'px');}});return $.Lunarity.referencePopup;});(function(window,$){"use strict";var module=window.dev.ReferencePopups;if(module.unloadCore){return $.noop;}module.unloadCore=$.noop;return function(callback){$.when(module.Popup).done(function(){callback(module,window,$,window.mediaWiki);}).fail(function(){delete module.unloadCore;});};}(window,jQuery))(function(module,window,$,mw){"use strict";var store={get:function(key){try{return JSON.parse(window.localStorage.getItem(key));}catch(e){return null;}},set:
function(key,data){try{window.localStorage.setItem(key,JSON.stringify(data));}catch(e){}}};var userConfig=(function(config,defaults){if(typeof(config)!=='object'||config===null){config={};}if(({hover:1,click:1})[config.react]!==1){config.react='hover';}config.hoverDelay=config.hoverDelay||defaults.hoverDelay||200;config.animate=(config.animate===void 0?defaults.animate===void 0||defaults.animate:!!config.animate);config.disabled=!!config.disabled&&!module.lockdown;config.stick=(config.stick===void 0?defaults.stick!==void 0&&defaults.stick:!!config.stick);return config;})(store.get('RefPopupsJS'),module.defaults||{});var armedPop=null,openPop=null;function cyclePopup(newTarget){if(openPop&&openPop.element.is(newTarget)){return;}if(armedPop){if(armedPop.element.is(newTarget)){return;}armedPop.destroy();}return(armedPop=constructPopup($(newTarget)));}function cleanupPopups(){if(openPop){openPop.destroy();}if(armedPop){armedPop.destroy();}openPop=armedPop=null;}$(function($){var lastTouch;
$('#mw-content-text').on({'touchEnd.RefPopups':function(ev){lastTouch=ev.originalEvent;},'click.RefPopups':function(ev){if(((!lastTouch||lastTouch.defaultPrevented)&&userConfig.react!=='click')||userConfig.disabled){return;}lastTouch=null;var pop=cyclePopup(this);if(pop){ev.preventDefault();pop.show(ev);}},'referencepopupopen.RefPopups':function(){if(!armedPop||!armedPop.element.is(this)){return;}var oldOpen=openPop;openPop=armedPop;armedPop=null;if(oldOpen){oldOpen.destroy();}},'referencepopupclose.RefPopups':function(){if(!openPop||!openPop.element.is(this)){return;}if(armedPop){openPop.destroy();}else{armedPop=openPop;}openPop=null;}},'.reference');$(window).on('pagehide.RefPopups',cleanupPopups);applyHoverEvents();});function applyHoverEvents(){var $article=$('#mw-content-text');$article.off('mouseenter.RefPopups');if(userConfig.disabled){return;}if(userConfig.react!=='hover'){if(openPop){openPop.option('activateBy','click');}if(armedPop){armedPop.option('activateBy','click');}
return;}$article.on('mouseenter.RefPopups','.reference',function(){var pop=cyclePopup(this);if(pop){pop.triggerHover();}});if(openPop){openPop.option('activateBy','hover');}if(armedPop){armedPop.option('activateBy','hover');}}if(!module.lockdown){$(function($){$('#articleCategories, #catlinks').first().after($('<a href="#configure-refpopups" class="refpopups-configure-page" />').html('['+module.messages.coreConfigureText+']').click(onClickConfigure).appendTo(this));});}module.unloadCore=function(){$('#mw-content-text').off('.RefPopups');$(window).off('.RefPopups');$('a[href="#configure-refpopups"]').remove();cleanupPopups();delete this.unloadCore;};$(window).trigger('dev-ReferencePopups-config',module.settings=$.extend({},userConfig));var configureIsPending=!1;function onClickConfigure(ev){ev.preventDefault();var closeFunc=function(){configureIsPending=!1;},interfaceFunc=function(confFunc){confFunc(userConfig,function(newSettings){store.set('RefPopupsJS',newSettings);
cleanupPopups();applyHoverEvents();$(window).trigger('dev-ReferencePopups-config',module.settings=$.extend({},newSettings));},closeFunc);};if(configureIsPending){return;}configureIsPending=!0;if(module.configure){$.when(module.configure).done(interfaceFunc).fail(closeFunc);return;}$.ajax({url:mw.config.get('wgLoadScript'),data:{mode:'articles',only:'scripts',articles:'w:dev:ReferencePopups/code.configure.js'},dataType:'script',cache:!0}).then(function(){$.when(module.configure).done(interfaceFunc).fail(closeFunc);}).fail(closeFunc);}function constructPopup($ref){var frag=$ref.find('a[href^="#cite_note"]').first();if(!frag.length){return null;}var $cite=$(frag.attr('href').replace(/\./g,'\\.'));if(!$cite.length){return null;}var $content=$('<div style="overflow:auto">'),$conf=$('<a href="#" class="refpopups-configure" />').prop('title',module.messages.coreConfigureHover).click(onClickConfigure);$content.append($cite.find('.reference-text').clone());return new module.Popup({content:
$conf.add($content),activateBy:userConfig.react,hoverDelay:userConfig.hoverDelay,animation:userConfig.animate&&'fold',stickyHover:userConfig.stick,contentBoxClass:'WikiaArticle'},$ref[0]);}});;;mw.loader.state({"wikia.fake.articles.f146595bd4b37d9666e8437662a2ddb7":"ready"});

/* cache key: fallout:resourceloader:filter:minify-js:7:28229f62aa1276f879e61aaa9b56f0fe */